/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abcew_videorecoder_ARecorder */

#ifndef _Included_com_abcew_videorecoder_ARecorder
#define _Included_com_abcew_videorecoder_ARecorder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_OUTPUT_FILE_DONE
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_OUTPUT_FILE_DONE 0L
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_LISTENER_DONE
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_LISTENER_DONE 1L
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_PARAMETER_DONE
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_PARAMETER_DONE 2L
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_PREVIEW_DONE
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_SET_PREVIEW_DONE 3L
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_START_DONE
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_START_DONE 4L
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_ERROR
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_ERROR 5L
#undef com_abcew_videorecoder_ARecorder_NATIVE_MSG_NOTIFY_LOG_INFO
#define com_abcew_videorecoder_ARecorder_NATIVE_MSG_NOTIFY_LOG_INFO 6L
/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeSetOutputFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeSetOutputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeSetChannels
 * Signature: (I)VnativeWriteVideo
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeSetChannels
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeSetSampleRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeSetSampleRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeSetVideoSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeSetVideoSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeSetColorFormat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeSetColorFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeWriteVideo
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeWriteVideo
  (JNIEnv *, jobject, jbyteArray, jint);


/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeWriteVideo
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeWriteAudio
        (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    setParameter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_setParameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeSetup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeSetup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_abcew_videorecoder_ARecorder
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_videorecoder_ARecorder_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
